name:  Deployment
on:
  push:
    branches:
      - main
concurrency:
  group: "dev"
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on server
        run: |
          curl https://s2.tmp1.dev/api/git/ERoepMPnljO04dwgkw8KxLWr158v6XQzDGmy/deploy
